[package]
name = "wirefilter-parser"
version = "0.1.0"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2018"

[dependencies]
cidr = "0.2.1"
pest_consume = "1.1.3"
pest = "2.5.6"
regex = { version = "1.7.1", default-features = false, features = ["std", "perf"] }
ordered-float = { version = "3.4.0", features = ["serde"] }

[dev-dependencies]
indoc = "2.0.1"
