[workspace]
members = ["ast-builder", "engine", "fuzz/bytes", "fuzz/map-keys"]

default-members = ["ast-builder", "engine"]

[profile.release]
panic = "unwind"
lto = true

[profile.dev]
panic = "unwind"
