[workspace]
members = [
	"ast-builder",
	"engine",
	"ffi",
	"fuzz/bytes",
	"fuzz/map-keys",
	"wasm",
	"wirefilter-parser",
]

default-members = ["ast-builder", "engine"]

[profile.release]
panic = "unwind"
lto = true

[profile.dev]
panic = "unwind"
