[project]
name = "python-ast-builder"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
