[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-engine"
version = "0.7.0"
description = "An execution engine for Wireshark-like filters"
readme = "README.md"
license = "MIT"
repository = "https://github.com/cloudflare/wirefilter"
keywords = ["wireshark", "filter", "engine", "parser", "runtime"]
categories = ["config", "parser-implementations"]
edition = "2018"

[lib]
name = "wirefilter"
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
cfg-if = "1.0.0"
cidr = { version = "0.2.1", features = ["serde"] }
derivative = "2.2.0"
fnv = "1.0.7"
indexmap = { version = "1.9.2", features = ["serde-1"] }
lazy_static = "1.4.0"
memmem = "0.1.1"
rand = "0.8.5"
regex = { version = "1.7.1", optional = true }
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
sliceslice = "0.4.1"
thiserror = "1.0.39"
ordered-float = { version = "3.4.0", features = ["serde"] }

[dev-dependencies]
criterion = "0.3.4"
indoc = "2.0.1"
lazy_static = "1.4.0"

[features]
default = ["regex"]
